blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [

    path('', views.PostListView.as_view(), name='list'),


    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),

  
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),


    path('buscar/', views.search_posts, name='search_posts'),

    path('autor/nuevo/', views.create_author, name='create_author'),
    path('categoria/nueva/', views.create_category, name='create_category'),
]

messaging/urls.py
from django.urls import path
from . import views

app_name = "messaging"

urlpatterns = [
    path('', views.inbox, name='inbox'),                      
    path('sent/', views.sent, name='sent'),                   
    path('new/', views.new_message, name='new_message'),      
    path('<int:pk>/', views.message_detail, name='detail'),   
    path('<int:pk>/reply/', views.reply_message, name='reply'),  
    path('<int:pk>/delete/', views.delete_message, name='delete'),

]

tuprimera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from blog.views import home, about

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('about/', about, name='about'),

    path('pages/', include('blog.urls')),
    path('accounts/', include('users.urls')),

    path('messages/', include('messaging.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"

urlpatterns = [

    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),

    path('logout/', views.user_logout, name='logout'),


    path('signup/', views.signup, name='signup'),


    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),


    path(
        'password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            success_url='/accounts/password_change_done/'
        ),
        name='password_change'
    ),

    path(
        'password_change_done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
]

templates/about.html
{% extends "base.html" %}
{% block title %}Acerca de mí{% endblock %}
{% block content %}
  <h1>Acerca de mí</h1>
  <p>Mi nombre es Leandro Rodriguez, soy desarrolador web y este sitio fue creado para mi Proyecto de Python</p>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Mi Blog{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
  <nav class="navbar">
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'about' %}">Acerca de mí</a>
    <a href="{% url 'blog:list' %}">Pages</a>

    {% if user.is_authenticated %}
    <a href="{% url 'users:profile' %}">Perfil</a>
    <a href="{% url 'messaging:inbox' %}">Mensajes</a>
    <a href="{% url 'users:logout' %}">Logout</a>
{% else %}
    <a href="{% url 'users:login' %}">Login</a>
    <a href="{% url 'users:signup' %}">Registro</a>
{% endif %}
</nav>

  <div class="messages">
    {% if messages %}
      {% for message in messages %}
        <p class="msg {{ message.tags }}">{{ message }}</p>
      {% endfor %}
    {% endif %}
  </div>

  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <footer class="footer">
    Proyecto Django Playground – {{ request.user.username|default:"Invitado" }}
  </footer>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
  <h1>Bienvenido a mi blog</h1>
  <p>Proyecto final Django Playground.</p>
{% endblock %}